jms_translation:
    configs:
        form_builder:
            dirs:
                - '%kernel.root_dir%/../vendor/ezsystems/ezplatform-form-builder/src'
            output_dir: '%kernel.root_dir%/../vendor/ezsystems/ezplatform-form-builder/src/bundle/Resources/translations/'
            excluded_dirs: [Behat, Tests]
            output_format: "xliff"
