parameters:
    page_builder.token_authenticator.enabled: true

jms_translation:
    configs:
        page_builder:
            dirs:
                - '%kernel.root_dir%/../vendor/ezsystems/ezplatform-page-builder/src'
            output_dir: '%kernel.root_dir%/../vendor/ezsystems/ezplatform-page-builder/src/bundle/Resources/translations/'
            excluded_dirs: [Behat, Tests]
            output_format: "xlf"
