# Tests cannot be run from metarepo - it's a public repository, which doesn't have access to private repositories on Travis (for security reasons).
# The actual test setup is in Page Builder bundle.
language: php
php:
  - '5.6'

script:
  - echo 'Test suite moved to PageBuilder bundle'
