# Siteaccesses are first added in ../ezplatform.yaml.
# Only merge additional siteaccesses here.

ezplatform:
    siteaccess:
        list:
            - other_site
        groups:
            site_group:
                - other_site
            sf_group_1: []
            sf_group_2: []
        default_siteaccess: site
        match:
            URIElement: 1
            '@EzSystems\EzPlatformSiteFactory\SiteAccessMatcher': ~
    system:
        sf_group_1:
            design: conference
        sf_group_2:
            design: roadshow

ezdesign:
    design_list:
        conference: [conference_template]
        roadshow: [roadshow_template]
    phpstorm:
        enabled: false

ez_platform_standard_design:
    override_kernel_templates: false

parameters:
    ezsettings.admin_group.notifications.success.timeout: 20000
    ezplatform.behat.enable_enterprise_services: true
